name: sooner

domains:
  - domain: www.sooner.app
    type: PRIMARY
  - domain: www.readitnow.app
    type: ALIAS

services:
  - name: api
    github:
      repo: arosiclair/sooner
      branch: production
      deploy_on_push: true
    run_command: npm run api
    environment_slug: node-js
    routes:
      - path: /api

static_sites:
  - name: ui
    github:
      repo: arosiclair/sooner
      branch: production
      deploy_on_push: true
    source_dir: ui
    environment_slug: node-js
    build_command: npm run build:app
    output_dir: packages/app/dist
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
