name: sooner

domains:
  - domain: www.sooner.app
    type: PRIMARY
  - domain: www.readitnow.app
    type: ALIAS

services:
  - name: api
    github:
      repo: arosiclair/read-it-now
      branch: master
      deploy_on_push: true
    source_dir: server
    environment_slug: node-js
    routes:
      - path: /api

static_sites:
  - name: ui
    github:
      repo: arosiclair/read-it-now
      branch: master
      deploy_on_push: true
    source_dir: ui
    environment_slug: node-js
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
